a = float(input("Introduce el primer número: "))
b = float(input("Introduce el segundo número: "))
print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)
print("División:", a / b)